name: bun CI

on:
  push:
    paths:
      - "cli-ascii-converter/**"
  pull_request:
    branch: [main]

jobs:
  setup:
    name: Setup Project
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
      - uses: actions/checkout@v4

      - name: Set up bun
      - uses: oven-sh/setup-bun@v2 
        with:
          node-version: "1.2.4"

      - name: Install dep & dev-dep
      - run: bun install
